### ISSUE TITLE
Hva skal nodejs.no være?

### ISSUE THREAD

**Issue by phillipj** [nodejs-no/www#1]
For øyeblikket er nodejs.no er redirect til nodejs.org. Nyttig kanskje, men kjedelige greier!

Store knapper / linker direkte til siste versjon node.js og io.js kunne har vært en grei start. Har lekt litt med tanken om å liste ut noen meetups også.

Noen som har noen tanker? Andre ting som hadde vært nyttig å vise?

**Comment by jestho** [comment]
Kanskje starte med noe så enkelt som en logo-vegg med norske selskaper som bruker node?

**Comment by leftieFriele** [comment]
Det som hadde vært fett ville vært å teamet opp med iojs.no folket som driver litt med samme greie. De er super ivrig og en bra gjeng https://github.com/iojs/iojs-no

**Comment by phillipj** [comment]
@jestho skrytevegg kunne vært bra :+1:

Takk for tipset @leftieFriele!

**Comment by Andersos** [comment]
Om det skal være skrytevegg burde jo noen skrive noe på http://tech.finn.no/ om hvordan Finn bruker Node/io *wink wink*

**Comment by phillipj** [comment]
Ja du sier noe der @Andersos, "noen" burde nok ta seg tid til det en dag :sunglasses:

**Comment by Andersos** [comment]
noen™

**Comment by jestho** [comment]
™<sup>™</sup>

**Comment by phillipj** [comment]
Nå som denne har fått gjære i all stillhet i 1.5 år, er det vel på tide å lukke denne.

Dette ideen om å lage no spesielt på nodejs.no oppsto i tider hvor vi som community mer eller mindre hadde gitt opp datidens eierskap av Node.js. Nå er det jo en stund siden io.js og Node.js merget sammen i et stort lykkelig ekteskap. Om noen™ føler for å starte med oversetting av dagens nodejs.org til norsk, som er fullt mulig pga locale-instillinger der, så er det bare å skrike ut! Da kan også peke nodejs.no mot den norskoversatte utgaven -- i mellomtiden er nodejs.no bare en enkel redirect til nodejs.org.
